# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b23eebb1fff0b3050733d9c8e5e5ff5d7b49fc323c4200760073bd01d34810a509648cb6b8bd6c5f2180002decadb3f9132335bb4d6dcb91422631595130e4ac

test:
  secret_key_base: c68228914af00ec32ba3dac5c31f589fefdc64a07ea57da5eab22832d8948b7371d03bca28ede2adeccef62dbf658d0ac1e1e09c609ec265616abc545b105a2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
